INSERT INTO [dbo].[Cidade] ([Id], [Nome], [EstadoId]) VALUES (1, N'Betim', 1)
INSERT INTO [dbo].[Cidade] ([Id], [Nome], [EstadoId]) VALUES (2, N'Belo Horizonte', 1)
INSERT INTO [dbo].[Cidade] ([Id], [Nome], [EstadoId]) VALUES (3, N'Contagem', 1)
INSERT INTO [dbo].[Cidade] ([Id], [Nome], [EstadoId]) VALUES (4, N'São João Del Rey', 1)
INSERT INTO [dbo].[Cidade] ([Id], [Nome], [EstadoId]) VALUES (5, N'Niterói', 20)
INSERT INTO [dbo].[Cidade] ([Id], [Nome], [EstadoId]) VALUES (6, N'Rio de Janeiro', 20)
INSERT INTO [dbo].[Cidade] ([Id], [Nome], [EstadoId]) VALUES (7, N'Brasília', 8)
INSERT INTO [dbo].[Cidade] ([Id], [Nome], [EstadoId]) VALUES (8, N'Limeira', 27)
INSERT INTO [dbo].[Cidade] ([Id], [Nome], [EstadoId]) VALUES (9, N'São Paulo', 27)
INSERT INTO [dbo].[Cidade] ([Id], [Nome], [EstadoId]) VALUES (10, N'Campinas', 27)
