INSERT INTO [dbo].[Estado] ([Id], [Nome], [UF]) VALUES (1, N'Minas Gerais', N'MG')
INSERT INTO [dbo].[Estado] ([Id], [Nome], [UF]) VALUES (2, N'Acre', N'AC')
INSERT INTO [dbo].[Estado] ([Id], [Nome], [UF]) VALUES (3, N'Alagoas', N'AL')
INSERT INTO [dbo].[Estado] ([Id], [Nome], [UF]) VALUES (4, N'Amazonas', N'AM')
INSERT INTO [dbo].[Estado] ([Id], [Nome], [UF]) VALUES (5, N'Amapá', N'AP')
INSERT INTO [dbo].[Estado] ([Id], [Nome], [UF]) VALUES (6, N'Bahia', N'BA')
INSERT INTO [dbo].[Estado] ([Id], [Nome], [UF]) VALUES (7, N'Ceará', N'CE')
INSERT INTO [dbo].[Estado] ([Id], [Nome], [UF]) VALUES (8, N'Distrito Federal', N'DF')
INSERT INTO [dbo].[Estado] ([Id], [Nome], [UF]) VALUES (9, N'Espírito Santo', N'ES')
INSERT INTO [dbo].[Estado] ([Id], [Nome], [UF]) VALUES (10, N'Goiás', N'GO')
INSERT INTO [dbo].[Estado] ([Id], [Nome], [UF]) VALUES (11, N'Maranhão', N'MA')
INSERT INTO [dbo].[Estado] ([Id], [Nome], [UF]) VALUES (13, N'Mato Grosso do Sul', N'MS')
INSERT INTO [dbo].[Estado] ([Id], [Nome], [UF]) VALUES (14, N'Mato Grosso', N'MT')
INSERT INTO [dbo].[Estado] ([Id], [Nome], [UF]) VALUES (15, N'Pará', N'PA')
INSERT INTO [dbo].[Estado] ([Id], [Nome], [UF]) VALUES (16, N'Paraíba', N'PB')
INSERT INTO [dbo].[Estado] ([Id], [Nome], [UF]) VALUES (17, N'Pernambuco', N'PE')
INSERT INTO [dbo].[Estado] ([Id], [Nome], [UF]) VALUES (18, N'Piauí', N'PI')
INSERT INTO [dbo].[Estado] ([Id], [Nome], [UF]) VALUES (19, N'Paraná', N'PR')
INSERT INTO [dbo].[Estado] ([Id], [Nome], [UF]) VALUES (20, N'Rio de Janeiro', N'RJ')
INSERT INTO [dbo].[Estado] ([Id], [Nome], [UF]) VALUES (21, N'Rio Grande do Norte', N'RN')
INSERT INTO [dbo].[Estado] ([Id], [Nome], [UF]) VALUES (22, N'Rondônia', N'RO')
INSERT INTO [dbo].[Estado] ([Id], [Nome], [UF]) VALUES (23, N'Roraima', N'RR')
INSERT INTO [dbo].[Estado] ([Id], [Nome], [UF]) VALUES (24, N'Rio Grande do Sul', N'RS')
INSERT INTO [dbo].[Estado] ([Id], [Nome], [UF]) VALUES (25, N'Santa Catarina', N'SC')
INSERT INTO [dbo].[Estado] ([Id], [Nome], [UF]) VALUES (26, N'Sergipe', N'SE')
INSERT INTO [dbo].[Estado] ([Id], [Nome], [UF]) VALUES (27, N'São Paulo', N'SP')
INSERT INTO [dbo].[Estado] ([Id], [Nome], [UF]) VALUES (28, N'Tocantins', N'TO')
